// lib/autoGenerateCertificate.ts
import { prisma } from './prisma';
import { generateCertificateCode, calculateGrade, isPassed } from './certificateUtils';

export async function checkAndGenerateCertificate(userId: number, courseId: number) {
  try {
    // ตรวจสอบว่ามี certificate แล้วหรือยัง
    const existingCert = await prisma.certificates.findFirst({
      where: {
        user_id: userId,
        course_id: courseId
      }
    });

    if (existingCert) {
      return { success: true, certificate: existingCert, alreadyExists: true };
    }

    // ตรวจสอบว่าเรียนจบแล้วหรือยัง
    const progress = await prisma.module_progress.findMany({
      where: {
        user_id: userId,
        course_id: courseId
      }
    });

    const course = await prisma.courses.findUnique({
      where: { id: courseId },
      include: {
        modules: true,
        user: {
          select: {
            username: true
          }
        }
      }
    });

    if (!course) {
      return { success: false, error: 'Course not found' };
    }

    const totalModules = course.modules.length;
    const completedModules = progress.filter(p => p.completed).length;

    // ต้องเรียนครบทุก module
    if (completedModules < totalModules) {
      return { success: false, error: 'Not all modules completed' };
    }

    // คำนวณคะแนนเฉลี่ย
    const testScores = progress.filter(p => p.test_score !== null && p.test_total !== null);
    const averageScore = testScores.length > 0
      ? Math.round(testScores.reduce((sum, p) => sum + ((p.test_score! / p.test_total!) * 100), 0) / testScores.length)
      : 0;

    // ตรวจสอบว่าผ่านเกณฑ์หรือไม่
    if (!isPassed(averageScore)) {
      return { success: false, error: 'Score below passing grade' };
    }

    // สร้าง certificate อัตโนมัติ
    const certificateCode = await generateCertificateCode(courseId, userId);
    const grade = calculateGrade(averageScore);

    const certificate = await prisma.certificates.create({
      data: {
        user_id: userId,
        course_id: courseId,
        certificate_code: certificateCode,
        completion_date: new Date(),
        grade,
        score: averageScore,
        instructor_name: course.user?.username || 'Unknown',
        course_title: course.title
      }
    });

    return { success: true, certificate, autoGenerated: true };
  } catch (error) {
    console.error('Error auto-generating certificate:', error);
    return { success: false, error: 'Failed to generate certificate' };
  }
}