// app/api/v0/modules/[moduleId]/progress/route.ts
import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { checkAndGenerateCertificate } from '@/lib/autoGenerateCertificate';

// GET - ดู progress ของ module
export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ moduleId: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({
        success: false,
        error: "Unauthorized"
      }, { status: 401 });
    }

    const user = session.user as any;
    const unwrappedParams = await params;
    const moduleId = parseInt(unwrappedParams.moduleId, 10);

    if (isNaN(moduleId)) {
      return NextResponse.json({
        success: false,
        error: "Invalid module ID"
      }, { status: 400 });
    }

    const progress = await prisma.module_progress.findUnique({
      where: {
        user_id_module_id: {
          user_id: user.id,
          module_id: moduleId
        }
      }
    });

    return NextResponse.json({
      success: true,
      progress: progress || null
    });

  } catch (error) {
    console.error("Error fetching progress:", error);
    return NextResponse.json({
      success: false,
      error: "Failed to fetch progress"
    }, { status: 500 });
  }
}

// POST - บันทึก progress
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ moduleId: string }> }
) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({
        success: false,
        error: "Unauthorized"
      }, { status: 401 });
    }

    const user = session.user as any;
    const unwrappedParams = await params;
    const moduleId = parseInt(unwrappedParams.moduleId, 10);

    if (isNaN(moduleId)) {
      return NextResponse.json({
        success: false,
        error: "Invalid module ID"
      }, { status: 400 });
    }

    const {
      courseId,
      preTestScore,
      preTestTotal,
      testScore,
      testTotal,
      videoCompleted,
      completed
    } = await req.json();

    // Get module info
    const module = await prisma.modules.findUnique({
      where: { id: moduleId },
      include: { courses: true }
    });

    if (!module) {
      return NextResponse.json({
        success: false,
        error: "Module not found"
      }, { status: 404 });
    }

    // Upsert progress
    const progress = await prisma.module_progress.upsert({
      where: {
        user_id_module_id: {
          user_id: user.id,
          module_id: moduleId
        }
      },
      update: {
        pre_test_score: preTestScore !== undefined ? preTestScore : undefined,
        pre_test_total: preTestTotal !== undefined ? preTestTotal : undefined,
        test_score: testScore !== undefined ? testScore : undefined,
        test_total: testTotal !== undefined ? testTotal : undefined,
        video_completed: videoCompleted !== undefined ? videoCompleted : undefined,
        completed: completed !== undefined ? completed : undefined,
        completed_at: completed ? new Date() : undefined
      },
      create: {
        user_id: user.id,
        module_id: moduleId,
        course_id: courseId || module.cid,
        pre_test_score: preTestScore || null,
        pre_test_total: preTestTotal || null,
        test_score: testScore || null,
        test_total: testTotal || null,
        video_completed: videoCompleted || false,
        completed: completed || false,
        completed_at: completed ? new Date() : null
      }
    });

    if (completed) {
      // ตรวจสอบว่าเรียนจบทั้ง course หรือยัง
      const allProgress = await prisma.module_progress.findMany({
        where: {
          user_id: user.id,
          course_id: courseId || module.cid
        }
      });

      const totalModules = await prisma.modules.count({
        where: { cid: courseId || module.cid }
      });

      const completedModules = allProgress.filter(p => p.completed).length;

      // ถ้าเรียนจบทุก module แล้ว พยายามสร้าง certificate
      if (completedModules === totalModules) {
        const certResult = await checkAndGenerateCertificate(
          user.id,
          courseId || module.cid
        );

        return NextResponse.json({
          success: true,
          message: "Progress saved",
          progress,
          courseCompleted: true,
          certificate: certResult.success ? certResult.certificate : null,
          certificateGenerated: certResult.success && certResult.autoGenerated
        });
      }
    }

    return NextResponse.json({
      success: true,
      message: "Progress saved",
      progress
    });

  } catch (error) {
    console.error("Error saving progress:", error);
    return NextResponse.json({
      success: false,
      error: "Failed to save progress"
    }, { status: 500 });
  }
}